# Generated by Django 5.0.4 on 2024-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoTrust",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("description", models.TextField()),
                ("picture", models.FileField(upload_to="updloads/svg")),
            ],
            options={
                "verbose_name": "Faire Confiance",
                "verbose_name_plural": "Faire Confiance",
            },
        ),
        migrations.CreateModel(
            name="Propriete2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("author", models.CharField(max_length=150)),
                ("validators_date", models.DateTimeField()),
                ("picture", models.FileField(upload_to="uploads/location")),
                (
                    "location_or_vendor",
                    models.CharField(
                        choices=[("location", "location"), ("vente", "vente")],
                        max_length=150,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maison à Vendre",
                "verbose_name_plural": "Maison à Vendre",
            },
        ),
    ]
