# Generated by Django 5.0.4 on 2024-05-08 10:17

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_dotrust_propriete2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whychoose",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
