# Generated by Django 5.0.4 on 2024-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('name_agency', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('site_web', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('name_representative', models.CharField(blank=True, max_length=150, null=True)),
                ('address_agency', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Agence Immobilière',
                'verbose_name_plural': 'Agence Immobilière',
            },
        ),
    ]
