# Generated by Django 5.0.4 on 2024-07-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_agencyrealestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('longitude', models.CharField(blank=True, max_length=150, null=True)),
                ('laltitude', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
            },
        ),
        migrations.DeleteModel(
            name='AgencyRealEstate',
        ),
    ]
