# Generated by Django 5.0.4 on 2024-07-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_typepropriete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typepropriete',
            old_name='name',
            new_name='libele',
        ),
    ]
