# Generated by Django 5.0.4 on 2024-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_name_typepropriete_libele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepropriete',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
