# Generated by Django 5.0.4 on 2024-07-10 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_social"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="social",
            options={
                "verbose_name": "Réseaux Social",
                "verbose_name_plural": "Réseaux Sociaux",
            },
        ),
    ]
