# Generated by Django 5.0.4 on 2024-08-06 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_cgu"),
        ("propriete", "0010_typepropriete_alter_proprietes_type_propriete"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TypePropriete",
        ),
    ]
