# Generated by Django 5.0.4 on 2024-08-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_typepropriete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Localite',
        ),
    ]
