# Generated by Django 5.0.4 on 2024-08-14 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_delete_localite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Propriete",
        ),
    ]
