# Generated by Django 5.0.4 on 2024-08-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_propriete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Propriete2',
        ),
    ]
