# Generated by Django 5.0.4 on 2025-05-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='subjet',
            new_name='subject',
        ),
    ]
