# Generated by Django 5.0.4 on 2024-07-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propriete", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propriete",
            name="picture",
        ),
        migrations.AddField(
            model_name="propriete",
            name="picture",
            field=models.ManyToManyField(to="propriete.photo"),
        ),
    ]
