# Generated by Django 5.0.4 on 2024-07-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriete', '0003_remove_propriete_picture_propriete_pictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propriete',
            new_name='Proprietes',
        ),
    ]
