# Generated by Django 5.0.4 on 2024-08-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propriete", "0004_rename_propriete_proprietes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proprietes",
            name="pictures",
        ),
        migrations.AddField(
            model_name="proprietes",
            name="pictures",
            field=models.ManyToManyField(to="propriete.photo"),
        ),
    ]
