# Generated by Django 5.0.4 on 2024-08-06 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("propriete", "0006_photo_name_alter_photo_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="name",
            new_name="title",
        ),
    ]
