# Generated by Django 5.0.4 on 2024-08-06 14:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriete', '0007_rename_name_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietes',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
