# Generated by Django 5.0.4 on 2024-08-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriete', '0010_typepropriete_alter_proprietes_type_propriete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('longitude', models.CharField(blank=True, max_length=150, null=True)),
                ('laltitude', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
            },
        ),
        migrations.RemoveField(
            model_name='proprietes',
            name='localité',
        ),
        migrations.AddField(
            model_name='proprietes',
            name='localite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='localite_propriete', to='propriete.localite'),
            preserve_default=False,
        ),
    ]
