# Generated by Django 5.0.4 on 2024-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriete', '0011_localite_remove_proprietes_localité_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristiqueMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('libele', models.CharField(blank=True, max_length=220, null=True)),
            ],
            options={
                'verbose_name': 'Caratéristiques des Maisons',
                'verbose_name_plural': 'Caratéristiques des Maisons',
            },
        ),
        migrations.AddField(
            model_name='proprietes',
            name='caracteristique_speciale',
            field=models.ManyToManyField(to='propriete.caracteristiquemaison'),
        ),
    ]
