# Generated by Django 5.0.4 on 2024-08-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriete', '0012_caracteristiquemaison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristiquemaison',
            name='name',
        ),
    ]
