# Generated by Django 5.0.4 on 2024-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propriete", "0013_remove_caracteristiquemaison_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proprietes",
            name="status",
            field=models.CharField(
                choices=[("à vendre", "à vendre"), ("à louer", "à louer")],
                max_length=15,
            ),
        ),
    ]
