# Generated by Django 5.2.5 on 2025-09-01 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partenariat", "0007_newsletters"),
        ("propriete", "0015_alter_proprietes_prix_propriete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proprietes",
            name="proprietaire_contact",
        ),
        migrations.AlterField(
            model_name="proprietes",
            name="localite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localite_propriete",
                to="propriete.localite",
            ),
        ),
        migrations.AlterField(
            model_name="proprietes",
            name="prix_propriete",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proprietes",
            name="proprietaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proprietes",
                to="partenariat.owner",
            ),
        ),
        migrations.AlterField(
            model_name="proprietes",
            name="type_propriete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="type_propriete_related",
                to="propriete.typepropriete",
            ),
        ),
    ]
