# Generated by Django 5.2.5 on 2025-09-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propriete", "0015_alter_proprietes_prix_propriete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proprietaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("nom", models.CharField(blank=True, max_length=220, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "verbose_name": "Propriétaire",
                "verbose_name_plural": "Propriétaires",
            },
        ),
        migrations.RemoveField(
            model_name="proprietes",
            name="proprietaire_contact",
        ),
        migrations.AlterField(
            model_name="proprietes",
            name="localite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localite_propriete",
                to="propriete.localite",
            ),
        ),
        migrations.AlterField(
            model_name="proprietes",
            name="prix_propriete",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proprietes",
            name="type_propriete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="type_propriete_related",
                to="propriete.typepropriete",
            ),
        ),
        migrations.AlterField(
            model_name="proprietes",
            name="proprietaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proprietes",
                to="propriete.proprietaire",
            ),
        ),
    ]
