# Generated by Django 5.2.4 on 2025-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "propriete",
            "0016_proprietaire_remove_proprietes_proprietaire_contact_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proprietaire",
            name="contact",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
