# Generated by Django 5.2.4 on 2025-10-14 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("propriete", "0017_proprietaire_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proprietaire",
            name="contact",
        ),
    ]
