# Generated by Django 5.0.4 on 2024-07-01 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partenariat", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Name",
            new_name="AgencyRealEstate",
        ),
    ]
