# Generated by Django 5.0.4 on 2024-07-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenariat', '0002_rename_name_agencyrealestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyrealestate',
            name='email',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
