# Generated by Django 5.0.4 on 2024-07-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partenariat", "0004_searcher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("phone", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(max_length=150)),
                (
                    "type_propriete",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                ("budjet", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "address_propriete",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "annee_construction",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "surface_habitable",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nbr_chambre",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nbr_salle_bain",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "caracteris_special",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
