# Generated by Django 5.0.4 on 2024-07-21 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partenariat", "0005_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owner",
            options={
                "verbose_name": "Proprietaire",
                "verbose_name_plural": "Proprietaires",
            },
        ),
    ]
