"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import redis
from pathlib import Path
from decouple import config
from core.utils import get_ip

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # App created
    'app',
    'partenariat',
    'propriete',
    'reserves',

    # App installed
    'tinymce',
    'colorfield', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

STATICFILES_DIRS = [BASE_DIR /'static']

STATIC_ROOT = BASE_DIR / 'static_cdn'

MEDIA_ROOT = BASE_DIR / 'media_cdn'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
APPEND_SLASH = False


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')


# Celery Configuration Options
# CELERY_BROKER_URL = f'redis://127.0.0.1:6379'
# CELERY_RESULT_BACKEND = f'redis://127.0.0.1:6379'

# r = redis.Redis(
#   host='electric-yeti-16169.upstash.io',
#   port=6379,
#   password='AT8pAAIjcDFmNDJlZjdhYTAxNjY0ODQ2OTk0NTJlZTZjOTAzMWZlYXAxMA',
#   ssl=True
# )


CELERY_BROKER_URL = f"redis://:AT8pAAIjcDFmNDJlZjdhYTAxNjY0ODQ2OTk0NTJlZTZjOTAzMWZlYXAxMA@electric-yeti-16169.upstash.io:6379?ssl_cert_reqs=required"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


JAZZMIN_SETTINGS = {
    
    "site_title": "Admin LouhSira",
    "site_header": "Tableau de Bord",
    "site_brand": "LouhSira Pro",
    "welcome_sign": "Bienvenue sur le panneau d’administration",
    "copyright": "LouhSira Pro © 2025",
    "hide_apps": [],  # Assure-toi que tes apps ne sont pas cachées ici
    "order_with_respect_to": ["app"],
    
    # Icône et logo
    "site_logo": "app/assets/img/LOGO_1_LOUHSIRAArtboard_1.svg",  # Mets ton logo dans /static/mon_app/logo.png
    "login_logo": "app/assets/img/LOGO_2_LOUHSIRAArtboard_1.svg", 
    
    # Menu de navigation
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Site Web", "url": "/", "new_window": True},
    ],
    
    # Organisation du menu latéral
    "custom_links": {
        "app": [{"name": "Ajouter une propriété", "url": "admin:propriete_proprietes_add", "icon": "fas fa-plus"}]
    },
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "web.Article": "fas fa-newspaper",
        "partenariat.AgencyRealEstate": "fas fa-handshake-simple",
        "partenariat.Searcher": "fas fa-landmark",
        "web.RendezVous": "fas fa-calendar-check",
        "partenariat.Owner": "fas fa-dice",
        "partenariat.Newsletters": "fas fa-envelope",
    },
   
    
    # Personnalisation des couleurs
    "theme": "cyborg",  # Essaye aussi "lux", "solar", "darkly", "flatly"...
}
